"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-05

Hand-written rather than autogenerated (no network access to install
SQLAlchemy/Alembic in the environment this was authored in to run
`alembic revision --autogenerate`). It is a direct, table-by-table
transcription of app/models/entities.py as of this commit.

If you change entities.py, either write the next migration by hand the same
way, or - once you have Alembic runnable against a real database - regenerate
from here with `alembic revision --autogenerate -m "..."` and review the
diff carefully; autogenerate does not reliably detect column-type changes,
renames, or check constraints.
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("username", sa.String(64), nullable=False),
        sa.Column("full_name", sa.String(128), nullable=False, server_default=""),
        sa.Column("service_number", sa.String(64), nullable=False, server_default=""),
        sa.Column("unit", sa.String(128), nullable=False, server_default=""),
        sa.Column("email", sa.String(255), nullable=True),
        sa.Column("password_hash", sa.String(128), nullable=False),
        sa.Column("pin_hash", sa.String(128), nullable=True),
        sa.Column("biometric_public_key", sa.Text(), nullable=True),
        sa.Column("role", sa.String(32), nullable=False, server_default="viewer"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("must_change_password", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("failed_logins", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trusted_device_ids", sa.Text(), nullable=False, server_default="[]"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_users_username", "users", ["username"], unique=True)
    op.create_index("ix_users_role", "users", ["role"])
    op.create_unique_constraint("uq_users_email", "users", ["email"])

    op.create_table(
        "components",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("component_id", sa.String(64), nullable=False),
        sa.Column("component_name", sa.String(255), nullable=False),
        sa.Column("part_number", sa.String(128), nullable=False, server_default=""),
        sa.Column("chip_number", sa.String(128), nullable=False, server_default=""),
        sa.Column("search_key", sa.String(128), nullable=False, server_default=""),
        sa.Column("manufacturer", sa.String(128), nullable=False, server_default=""),
        sa.Column("manufacturer_country", sa.String(64), nullable=False, server_default=""),
        sa.Column("country_of_origin", sa.String(64), nullable=False, server_default=""),
        sa.Column("is_chinese", sa.String(8), nullable=False, server_default="UNKNOWN"),
        sa.Column("category", sa.String(64), nullable=False, server_default=""),
        sa.Column("drone_subsystem", sa.String(64), nullable=False, server_default=""),
        sa.Column("criticality", sa.String(16), nullable=False, server_default="REVIEW"),
        sa.Column("criticality_policy", sa.Text(), nullable=False, server_default=""),
        sa.Column("alternative_manufacturer", sa.Text(), nullable=False, server_default=""),
        sa.Column("military_grade", sa.String(8), nullable=False, server_default="NO"),
        sa.Column("barcode", sa.String(64), nullable=False, server_default=""),
        sa.Column("qr_code", sa.String(255), nullable=False, server_default=""),
        sa.Column("function", sa.String(255), nullable=False, server_default=""),
        sa.Column("remarks", sa.Text(), nullable=False, server_default=""),
        sa.Column("image_path", sa.String(512), nullable=False, server_default=""),
        sa.Column("datasheet_url", sa.String(512), nullable=False, server_default=""),
        sa.Column("supplier", sa.String(255), nullable=False, server_default=""),
        sa.Column("verified_by", sa.String(128), nullable=False, server_default=""),
        sa.Column("verification_source", sa.String(255), nullable=False, server_default=""),
        sa.Column("confidence_score", sa.Float(), nullable=False, server_default="100.0"),
        sa.Column("pending_verification", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("revision", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("is_deleted", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("source_batch_id", sa.String(36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_components_component_id", "components", ["component_id"], unique=True)
    op.create_index("ix_components_component_name", "components", ["component_name"])
    op.create_index("ix_components_part_number", "components", ["part_number"])
    op.create_index("ix_components_chip_number", "components", ["chip_number"])
    op.create_index("ix_components_manufacturer", "components", ["manufacturer"])
    op.create_index("ix_components_country_of_origin", "components", ["country_of_origin"])
    op.create_index("ix_components_is_chinese", "components", ["is_chinese"])
    op.create_index("ix_components_category", "components", ["category"])
    op.create_index("ix_components_drone_subsystem", "components", ["drone_subsystem"])
    op.create_index("ix_components_barcode", "components", ["barcode"])
    op.create_index("ix_components_pending_verification", "components", ["pending_verification"])
    op.create_index("ix_components_is_deleted", "components", ["is_deleted"])
    op.create_index("ix_components_source_batch_id", "components", ["source_batch_id"])
    op.create_index("ix_components_search_key", "components", ["search_key"])
    op.create_index("ix_components_origin", "components", ["is_chinese", "criticality"])
    op.create_index("ix_components_mfr_part", "components", ["manufacturer", "part_number"])

    op.create_table(
        "component_revisions",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("component_pk", sa.String(36), nullable=False),
        sa.Column("component_id", sa.String(64), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("operation", sa.String(16), nullable=False),
        sa.Column("snapshot_json", sa.Text(), nullable=False),
        sa.Column("changed_fields", sa.Text(), nullable=False, server_default="[]"),
        sa.Column("batch_id", sa.String(36), nullable=True),
        sa.Column("actor_id", sa.String(36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_component_revisions_component_pk", "component_revisions", ["component_pk"])
    op.create_index("ix_component_revisions_component_id", "component_revisions", ["component_id"])
    op.create_index("ix_component_revisions_batch_id", "component_revisions", ["batch_id"])

    op.create_table(
        "import_batches",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("filename", sa.String(255), nullable=False),
        sa.Column("file_sha256", sa.String(64), nullable=False),
        sa.Column("file_format", sa.String(16), nullable=False),
        sa.Column("status", sa.String(16), nullable=False, server_default="staged"),
        sa.Column("rows_total", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("rows_new", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("rows_updated", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("rows_unchanged", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("rows_deleted", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("rows_duplicate", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("rows_invalid", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("summary_json", sa.Text(), nullable=False, server_default="{}"),
        sa.Column("error_log", sa.Text(), nullable=False, server_default=""),
        sa.Column("actor_id", sa.String(36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("committed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_import_batches_file_sha256", "import_batches", ["file_sha256"])

    op.create_table(
        "inspections",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("inspection_number", sa.String(64), nullable=False),
        sa.Column("title", sa.String(255), nullable=False, server_default=""),
        sa.Column("platform", sa.String(128), nullable=False, server_default=""),
        sa.Column("serial_number", sa.String(128), nullable=False, server_default=""),
        sa.Column("inspector_id", sa.String(36), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("location", sa.String(255), nullable=False, server_default=""),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(24), nullable=False, server_default="open"),
        sa.Column("verdict", sa.String(24), nullable=False, server_default="pending"),
        sa.Column("remarks", sa.Text(), nullable=False, server_default=""),
        sa.Column("signature", sa.String(64), nullable=True),
        sa.Column("signed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_inspections_inspection_number", "inspections", ["inspection_number"],
                    unique=True)
    op.create_index("ix_inspections_inspector_id", "inspections", ["inspector_id"])

    op.create_table(
        "scan_records",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("client_uuid", sa.String(36), nullable=False),
        sa.Column("inspection_id", sa.String(36), sa.ForeignKey("inspections.id"), nullable=True),
        sa.Column("user_id", sa.String(36), nullable=False),
        sa.Column("input_mode", sa.String(16), nullable=False),
        sa.Column("raw_input", sa.String(512), nullable=False, server_default=""),
        sa.Column("normalized_input", sa.String(512), nullable=False, server_default=""),
        sa.Column("ocr_text", sa.Text(), nullable=False, server_default=""),
        sa.Column("barcode_symbology", sa.String(32), nullable=False, server_default=""),
        sa.Column("matched_component_id", sa.String(64), nullable=True),
        sa.Column("match_method", sa.String(24), nullable=False, server_default=""),
        sa.Column("match_score", sa.Float(), nullable=False, server_default="0.0"),
        sa.Column("result", sa.String(24), nullable=False),
        sa.Column("criticality", sa.String(16), nullable=False, server_default=""),
        sa.Column("device_id", sa.String(128), nullable=False, server_default=""),
        sa.Column("device_model", sa.String(128), nullable=False, server_default=""),
        sa.Column("app_version", sa.String(32), nullable=False, server_default=""),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("location_label", sa.String(255), nullable=False, server_default=""),
        sa.Column("image_paths", sa.Text(), nullable=False, server_default="[]"),
        sa.Column("duration_ms", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("remarks", sa.Text(), nullable=False, server_default=""),
        sa.Column("scanned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_scan_records_client_uuid", "scan_records", ["client_uuid"], unique=True)
    op.create_index("ix_scan_records_inspection_id", "scan_records", ["inspection_id"])
    op.create_index("ix_scan_records_user_id", "scan_records", ["user_id"])
    op.create_index("ix_scan_records_normalized_input", "scan_records", ["normalized_input"])
    op.create_index("ix_scan_records_matched_component_id", "scan_records", ["matched_component_id"])
    op.create_index("ix_scan_records_result", "scan_records", ["result"])
    op.create_index("ix_scan_records_scanned_at", "scan_records", ["scanned_at"])
    op.create_index("ix_scan_time_result", "scan_records", ["scanned_at", "result"])

    op.create_table(
        "pending_components",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("raw_input", sa.String(512), nullable=False),
        sa.Column("normalized_input", sa.String(512), nullable=False),
        sa.Column("ocr_text", sa.Text(), nullable=False, server_default=""),
        sa.Column("suggested_matches", sa.Text(), nullable=False, server_default="[]"),
        sa.Column("image_paths", sa.Text(), nullable=False, server_default="[]"),
        sa.Column("reported_by", sa.String(36), nullable=False),
        sa.Column("hit_count", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("status", sa.String(16), nullable=False, server_default="open"),
        sa.Column("resolution_note", sa.Text(), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_pending_components_normalized_input", "pending_components",
                    ["normalized_input"])

    op.create_table(
        "audit_log",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("sequence", sa.Integer(), nullable=False),  # app-assigned, not DB-autoincremented - see entities.py
        sa.Column("actor_id", sa.String(36), nullable=True),
        sa.Column("actor_username", sa.String(64), nullable=False, server_default=""),
        sa.Column("action", sa.String(64), nullable=False),
        sa.Column("entity_type", sa.String(64), nullable=False, server_default=""),
        sa.Column("entity_id", sa.String(64), nullable=False, server_default=""),
        sa.Column("detail_json", sa.Text(), nullable=False, server_default="{}"),
        sa.Column("ip_address", sa.String(64), nullable=False, server_default=""),
        sa.Column("user_agent", sa.String(255), nullable=False, server_default=""),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("prev_hash", sa.String(64), nullable=False, server_default="0" * 64),
        sa.Column("hash", sa.String(64), nullable=False),
        sa.UniqueConstraint("sequence", name="uq_audit_sequence"),
    )
    op.create_index("ix_audit_log_sequence", "audit_log", ["sequence"])
    op.create_index("ix_audit_log_action", "audit_log", ["action"])
    op.create_index("ix_audit_log_occurred_at", "audit_log", ["occurred_at"])

    op.create_table(
        "sync_state",
        sa.Column("device_id", sa.String(128), primary_key=True),
        sa.Column("user_id", sa.String(36), nullable=False),
        sa.Column("last_pull_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_push_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("db_revision", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("pending_conflicts", sa.Text(), nullable=False, server_default="[]"),
    )


def downgrade() -> None:
    op.drop_table("sync_state")
    op.drop_table("audit_log")
    op.drop_table("pending_components")
    op.drop_table("scan_records")
    op.drop_table("inspections")
    op.drop_table("import_batches")
    op.drop_table("component_revisions")
    op.drop_table("components")
    op.drop_table("users")
